name: pipeline

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: build
        run: cargo test --no-run

      - name: test
        run: cargo test -- --nocapture --quiet

      - name: formatting
        run: cargo fmt --all -- --check

      - name: check
        run: cargo check

      - name: clippy
        run: cargo clippy -- -D warnings
